# Generated by Django 3.2.9 on 2021-11-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManagement', '0006_auto_20211107_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.ImageField(upload_to='media'),
        ),
    ]
